/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVendasRouteImport } from './routes/app.vendas'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppProducaoRouteImport } from './routes/app.producao'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEstoqueRouteImport } from './routes/app.estoque'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppComercialRouteImport } from './routes/app.comercial'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAssistenteRouteImport } from './routes/app.assistente'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoRoute = AppProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComercialRoute = AppComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistenteRoute = AppAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comercial': typeof AppComercialRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/producao': typeof AppProducaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comercial': typeof AppComercialRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/producao': typeof AppProducaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/vendas': typeof AppVendasRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comercial': typeof AppComercialRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/producao': typeof AppProducaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/app/assistente'
    | '/app/clientes'
    | '/app/comercial'
    | '/app/configuracoes'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/producao'
    | '/app/relatorios'
    | '/app/vendas'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/app/assistente'
    | '/app/clientes'
    | '/app/comercial'
    | '/app/configuracoes'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/producao'
    | '/app/relatorios'
    | '/app/vendas'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/app/assistente'
    | '/app/clientes'
    | '/app/comercial'
    | '/app/configuracoes'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/producao'
    | '/app/relatorios'
    | '/app/vendas'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendas': {
      id: '/app/vendas'
      path: '/vendas'
      fullPath: '/app/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/producao': {
      id: '/app/producao'
      path: '/producao'
      fullPath: '/app/producao'
      preLoaderRoute: typeof AppProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comercial': {
      id: '/app/comercial'
      path: '/comercial'
      fullPath: '/app/comercial'
      preLoaderRoute: typeof AppComercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistente': {
      id: '/app/assistente'
      path: '/assistente'
      fullPath: '/app/assistente'
      preLoaderRoute: typeof AppAssistenteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistenteRoute: typeof AppAssistenteRoute
  AppClientesRoute: typeof AppClientesRoute
  AppComercialRoute: typeof AppComercialRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppProducaoRoute: typeof AppProducaoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppVendasRoute: typeof AppVendasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistenteRoute: AppAssistenteRoute,
  AppClientesRoute: AppClientesRoute,
  AppComercialRoute: AppComercialRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppProducaoRoute: AppProducaoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppVendasRoute: AppVendasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
